version: "3.8"

services:
  snappier-server:
    image: ghcr.io/rydizz214/snappier-server-docker:0.0.0t
    container_name: snappier-server
    restart: unless-stopped

    ports:
      - "7429:8000"

    environment:
      PORT: "8000"
      ENABLE_REMUX: "true"
      DOWNLOAD_SPEED_LIMIT_MBS: "10"
      USE_FFMPEG_TO_DOWNLOAD: "false"
      # Set to "true" if you want to use ffmpeg for downloads

      # If you wish to override folder locations, uncomment & edit below:
      # RECORDINGS_FOLDER: "/root/SnappierServer/recordings"
      # MOVIES_FOLDER: "/root/SnappierServer/movies"
      # SERIES_FOLDER: "/root/SnappierServer/series"
      # PVR_FOLDER: "/root/SnappierServer/pvr"

    volumes:
      - /data/recordings/snappier-server/recordings:/root/SnappierServer/recordings
      - /data/recordings/snappier-server/movies:/root/SnappierServer/movies
      - /data/recordings/snappier-server/series:/root/SnappierServer/series
      - /data/recordings/snappier-server/pvr:/root/SnappierServer/pvr
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "-f"
        - "http://127.0.0.1:8000/serverStats"
      interval: 60s
      timeout: 5s
      retries: 3
