version: "3.8"

services:
  snappier-server:
    build:
      context: .
      args:
        SNAPPIER_VERSION: "0.8.0p"
    image: rydizz214/snappier-server:0.8.0p
    container_name: snappier-server
    restart: unless-stopped

    environment:
      PORT:                     "8000"
      ENABLE_REMUX:             "true"
      RECORDINGS_FOLDER:        "/root/SnappierServer/Recordings"
      MOVIES_FOLDER:            "/root/SnappierServer/Movies"
      SERIES_FOLDER:            "/root/SnappierServer/TVSeries"
      PVR_FOLDER:               "/root/SnappierServer/PVR"
      DOWNLOAD_SPEED_LIMIT_MBS: "50"

    volumes:
      - "/data/recordings/snappier-server/Recordings:/root/SnappierServer/Recordings"
      - "/data/recordings/snappier-server/Movies:/root/SnappierServer/Movies"
      - "/data/recordings/snappier-server/TVSeries:/root/SnappierServer/TVSeries"
      - "/data/recordings/snappier-server/PVR:/root/SnappierServer/PVR"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

    ports:
      - "7429:8000"

    healthcheck:
      test: [
        "CMD",
        "curl", "-f", "-X", "GET",
        "http://127.0.0.1:8000/serverStats",
        "-H", "Accept: application/json"
      ]
      interval: 60s
      timeout: 5s
      retries: 3
      # ⚠️ If you change API_PORT from 8000, update the URL here.

