services:
  snappier-server:
    image: ghcr.io/rydizz214/snappier-server-docker:${SNAPPIER_SERVER_VERSION}
    container_name: snappier-server
    restart: unless-stopped

    build:
      context: .
      dockerfile: Dockerfile
      args:
        SNAPPIER_SERVER_VERSION: "${SNAPPIER_SERVER_VERSION}"

    env_file:
      - .env

    ports:
      - "${HOST_PORT}:${PORT}"
      - "${NOTIFY_HTTP_PORT}:${NOTIFY_HTTP_PORT}"
      - "${NOTIFY_WS_PORT}:${NOTIFY_WS_PORT}"

    environment:
      USE_CURL_TO_DOWNLOAD:     "${USE_CURL_TO_DOWNLOAD}"
      DOWNLOAD_SPEED_LIMIT_MBS: "${DOWNLOAD_SPEED_LIMIT_MBS}"

      # Optional notification webhooks
      PUSHOVER_USER_KEY:        "${PUSHOVER_USER_KEY}"
      PUSHOVER_API_TOKEN:       "${PUSHOVER_API_TOKEN}"
      NTFY_TOPIC:               "${NTFY_TOPIC}"
      TELEGRAM_TOKEN:           "${TELEGRAM_TOKEN}"
      TELEGRAM_CHAT_ID:         "${TELEGRAM_CHAT_ID}"
      DISCORD_WEBHOOK_URL:      "${DISCORD_WEBHOOK_URL}"

    # Optional: bind host directories for media (uncomment to utilize)
    #volumes:
    #  - /data/recordings/snappier-server/Recordings:/root/SnappierServer/Recordings
    #  - /data/recordings/snappier-server/Movies:/root/SnappierServer/Movies
    #  - /data/recordings/snappier-server/TVSeries:/root/SnappierServer/TVSeries
    #  - /data/recordings/snappier-server/PVR:/root/SnappierServer/PVR

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${PORT}/serverStats"]
      interval: 60s
      timeout: 5s
      retries: 3
